Repository prgrms-web-devcourse/Team-10jo-10wonmoa-BE, pull requests merged in 2022-07, with the labels that each got.

#7 [#6] CustomDataJpaTest 어노테이션
  src/test/java/com/prgrms/tenwonmoa/common/annotation/CustomDataJpaTest.java
  src/test/java/com/prgrms/tenwonmoa/config/TestConfig.java
Labels: feature

#3 [#2] Exception과 Handler 초기 작성
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/Expenditure.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/Income.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/repository/ExpenditureRepository.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/repository/IncomeRepository.java
  src/main/java/com/prgrms/tenwonmoa/domain/common/BaseEntity.java
  src/main/java/com/prgrms/tenwonmoa/exception/AlreadyExistException.java
  src/main/java/com/prgrms/tenwonmoa/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/prgrms/tenwonmoa/exception/message/Message.java
  src/main/java/com/prgrms/tenwonmoa/exception/response/ErrorResponse.java
Labels: feature

#18 [#13] 수입도메인 유효성 검사
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/AccountBookConst.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/Income.java
  src/main/java/com/prgrms/tenwonmoa/exception/message/Message.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/IncomeTest.java
Labels: feature

#17 [#9] 사용자는 지출을 등록할 수 있다.
  build.gradle
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/Expenditure.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/controller/ExpenditureController.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/dto/CreateExpenditureRequest.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/dto/CreateExpenditureResponse.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/service/ExpenditureService.java
  src/main/java/com/prgrms/tenwonmoa/exception/message/Message.java
  src/test/java/com/prgrms/tenwonmoa/common/annotation/CustomDataJpaTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/ExpenditureTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/service/ExpenditureServiceTest.java
Labels: feature

#19 [#14] 카테고리 등록 서비스 구현
  src/main/java/com/prgrms/tenwonmoa/domain/category/dto/service/SingleCategoryResult.java
  src/main/java/com/prgrms/tenwonmoa/domain/category/repository/CategoryRepository.java
  src/main/java/com/prgrms/tenwonmoa/domain/category/repository/UserCategoryRepository.java
  src/main/java/com/prgrms/tenwonmoa/domain/category/service/CategoryService.java
  src/main/java/com/prgrms/tenwonmoa/exception/message/Message.java
  src/test/java/com/prgrms/tenwonmoa/domain/category/service/CategoryServiceTest.java
Labels: feature

#25 [#20] 카테고리 수정 서비스 구현
  src/main/java/com/prgrms/tenwonmoa/domain/category/Category.java
  src/main/java/com/prgrms/tenwonmoa/domain/category/repository/UserCategoryRepository.java
  src/main/java/com/prgrms/tenwonmoa/domain/category/service/CategoryService.java
  src/test/java/com/prgrms/tenwonmoa/domain/category/repository/UserCategoryRepositoryTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/category/service/CategoryServiceTest.java
Labels: feature

#27 [#1] 유저 도메인 유효성 검사
  src/main/java/com/prgrms/tenwonmoa/domain/user/User.java
  src/main/java/com/prgrms/tenwonmoa/domain/user/UserConst.java
  src/main/java/com/prgrms/tenwonmoa/exception/message/Message.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/ExpenditureTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/service/ExpenditureServiceTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/user/UserTest.java
Labels: feature

#28 [#22] 사용자는 지출을 수정할 수 있다.
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/Expenditure.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/controller/ExpenditureController.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/dto/UpdateExpenditureRequest.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/service/ExpenditureService.java
  src/main/java/com/prgrms/tenwonmoa/exception/message/Message.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/ExpenditureTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/service/ExpenditureServiceTest.java
Labels: feature

#30 [#29] 수입등록 서비스 구현 - Service
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/dto/CreateIncomeRequest.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/service/AccountBookService.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/service/IncomeService.java
  src/main/java/com/prgrms/tenwonmoa/domain/category/repository/UserCategoryRepository.java
  src/main/java/com/prgrms/tenwonmoa/domain/category/service/UserCategoryService.java
  src/main/java/com/prgrms/tenwonmoa/domain/user/service/UserService.java
  src/test/java/com/prgrms/tenwonmoa/common/fixture/Fixture.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/service/AccountBookServiceTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/service/IncomeServiceTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/category/repository/UserCategoryRepositoryTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/category/service/UserCategoryServiceTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/user/service/UserServiceTest.java
Labels: feature

#33 [#26] 사용자는 카테고리를 삭제할 수 있다 - Service
  src/main/java/com/prgrms/tenwonmoa/domain/category/service/CategoryService.java
  src/test/java/com/prgrms/tenwonmoa/domain/category/CategoryTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/category/UserCategoryTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/category/repository/UserCategoryRepositoryTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/category/service/CategoryServiceTest.java
Labels: feature

#36 [#23] 사용자는 지출을 삭제할 수 있다.
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/Expenditure.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/controller/ExpenditureController.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/dto/CreateExpenditureRequest.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/service/ExpenditureService.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/service/ExpenditureServiceTest.java
Labels: feature

#44 [#43] AccountBookService 이름 변경
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/service/IncomeTotalService.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/service/IncomeTotalServiceTest.java
Labels: refactor

#38 [#35] User 등록 기능 추가 - Service
  src/main/java/com/prgrms/tenwonmoa/domain/user/dto/CreateUserRequest.java
  src/main/java/com/prgrms/tenwonmoa/domain/user/repository/UserRepository.java
  src/main/java/com/prgrms/tenwonmoa/domain/user/service/UserService.java
  src/main/java/com/prgrms/tenwonmoa/exception/message/Message.java
  src/test/java/com/prgrms/tenwonmoa/domain/user/service/UserServiceTest.java
Labels: feature

#40 [#24] 사용자는 지출을 조회할 수 있다.
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/Expenditure.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/controller/ExpenditureController.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/dto/CreateExpenditureResponse.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/dto/FindExpenditureResponse.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/service/ExpenditureService.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/ExpenditureTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/service/ExpenditureServiceTest.java
Labels: feature

#41 [#31] 사용자는 수입을 등록할 수 있다. - Controller
  build.gradle
  docs/income.adoc
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/controller/IncomeController.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/dto/CreateIncomeRequest.java
  src/main/java/com/prgrms/tenwonmoa/exception/handler/GlobalExceptionHandler.java
  src/test/java/com/prgrms/tenwonmoa/common/documentdto/CreateIncomeRequestDoc.java
  src/test/java/com/prgrms/tenwonmoa/common/documentdto/ErrorResponseDoc.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/controller/IncomeControllerTest.java
Labels: feature

#47 [#39] User 등록 기능 - Controller
  docs/user.adoc
  src/main/java/com/prgrms/tenwonmoa/domain/user/controller/UserController.java
  src/main/java/com/prgrms/tenwonmoa/domain/user/dto/CreateUserRequest.java
  src/main/java/com/prgrms/tenwonmoa/domain/user/service/UserService.java
  src/main/java/com/prgrms/tenwonmoa/exception/handler/GlobalExceptionHandler.java
  src/test/java/com/prgrms/tenwonmoa/domain/user/controller/UserControllerTest.java
Labels: feature

#49 [#48] 카테고리 등록 로직 리팩토링
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/service/IncomeTotalService.java
  src/main/java/com/prgrms/tenwonmoa/domain/category/service/CategoryService.java
  src/main/java/com/prgrms/tenwonmoa/domain/category/service/UserCategoryService.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/service/IncomeTotalServiceTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/category/service/CategoryServiceTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/category/service/UserCategoryServiceTest.java
Labels: refactor

#55 [#42] 수입 상세조회 구현
  docs/income.adoc
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/controller/IncomeController.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/dto/FindIncomeResponse.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/repository/IncomeRepository.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/service/IncomeService.java
  src/main/java/com/prgrms/tenwonmoa/exception/message/Message.java
  src/test/java/com/prgrms/tenwonmoa/common/RepositoryTest.java
  src/test/java/com/prgrms/tenwonmoa/common/documentdto/FindIncomeResponseDoc.java
  src/test/java/com/prgrms/tenwonmoa/common/fixture/Fixture.java
  src/test/java/com/prgrms/tenwonmoa/common/fixture/RepositoryFixture.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/controller/IncomeControllerTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/repository/IncomeRepositoryTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/service/IncomeServiceTest.java
Labels: feature

#53 [#37] 카테고리 등록, 수정, 삭제 로직 구현
  docs/income.adoc
  docs/user.adoc
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/Income.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/controller/IncomeController.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/repository/ExpenditureRepository.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/repository/IncomeRepository.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/service/ExpenditureService.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/service/IncomeService.java
  src/main/java/com/prgrms/tenwonmoa/domain/category/repository/UserCategoryRepository.java
  src/main/java/com/prgrms/tenwonmoa/domain/category/service/CategoryService.java
  src/main/java/com/prgrms/tenwonmoa/domain/category/service/UserCategoryService.java
  src/main/java/com/prgrms/tenwonmoa/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/prgrms/tenwonmoa/exception/message/Message.java
  src/test/java/com/prgrms/tenwonmoa/common/fixture/Fixture.java
  src/test/java/com/prgrms/tenwonmoa/common/fixture/RepositoryFixture.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/IncomeTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/controller/IncomeControllerTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/repository/ExpenditureRepositoryTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/repository/IncomeRepositoryTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/service/ExpenditureServiceTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/service/IncomeTotalServiceTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/category/repository/UserCategoryRepositoryTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/category/service/CategoryServiceTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/category/service/UserCategoryServiceTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/user/controller/UserControllerTest.java
Labels: feature

#58 [#52] Fixture 사용방법 변경, 사용케이스 변경
  src/test/java/com/prgrms/tenwonmoa/common/fixture/Fixture.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/repository/IncomeRepositoryTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/service/IncomeServiceTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/service/IncomeTotalServiceTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/category/service/UserCategoryServiceTest.java
Labels: refactor

#61 [#60] 수입 타입변경
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/Income.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/dto/CreateIncomeRequest.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/dto/FindIncomeResponse.java
  src/test/java/com/prgrms/tenwonmoa/common/fixture/Fixture.java
  src/test/java/com/prgrms/tenwonmoa/common/fixture/RepositoryFixture.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/IncomeTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/controller/IncomeControllerTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/service/IncomeTotalServiceTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/category/service/UserCategoryServiceTest.java
Labels: refactor

#62 [#59] 지출의 registerDate를 LocalDateTime으로
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/Expenditure.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/dto/CreateExpenditureRequest.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/dto/FindExpenditureResponse.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/dto/UpdateExpenditureRequest.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/repository/ExpenditureCustomRepository.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/repository/ExpenditureRepository.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/repository/ExpenditureRepositoryImpl.java
  src/main/java/com/prgrms/tenwonmoa/domain/common/BaseEntity.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/ExpenditureTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/repository/ExpenditureRepositoryTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/service/ExpenditureServiceTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/category/service/UserCategoryServiceTest.java
Labels: bug

#63 [#54] 카테고리 이름 수정 서비스 구현
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/Income.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/repository/ExpenditureRepository.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/repository/IncomeRepository.java
  src/main/java/com/prgrms/tenwonmoa/domain/category/repository/UserCategoryRepository.java
  src/main/java/com/prgrms/tenwonmoa/domain/category/service/UserCategoryService.java
  src/test/java/com/prgrms/tenwonmoa/common/fixture/Fixture.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/IncomeTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/repository/IncomeRepositoryTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/category/service/UserCategoryServiceTest.java
Labels: feature

#65 [#56] 유저가 가지고 있는 카테고리 조회 서비스 - Service
  src/main/java/com/prgrms/tenwonmoa/domain/category/UserCategory.java
  src/main/java/com/prgrms/tenwonmoa/domain/category/dto/FindCategoryResponse.java
  src/main/java/com/prgrms/tenwonmoa/domain/category/dto/service/SingleCategoryResult.java
  src/main/java/com/prgrms/tenwonmoa/domain/category/repository/UserCategoryRepository.java
  src/main/java/com/prgrms/tenwonmoa/domain/category/service/FindUserCategoryService.java
  src/test/java/com/prgrms/tenwonmoa/common/fixture/Fixture.java
  src/test/java/com/prgrms/tenwonmoa/common/fixture/RepositoryFixture.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/repository/ExpenditureRepositoryTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/repository/IncomeRepositoryTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/service/IncomeServiceTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/service/IncomeTotalServiceTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/category/UserCategoryTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/category/repository/UserCategoryRepositoryTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/category/service/FindUserCategoryServiceTest.java
Labels: feature

#67 [#46] 유저 로그인
  build.gradle
  src/main/java/com/prgrms/tenwonmoa/config/JwtConfigure.java
  src/main/java/com/prgrms/tenwonmoa/config/WebSecurityConfig.java
  src/main/java/com/prgrms/tenwonmoa/domain/user/User.java
  src/main/java/com/prgrms/tenwonmoa/domain/user/controller/UserController.java
  src/main/java/com/prgrms/tenwonmoa/domain/user/dto/LoginUserRequest.java
  src/main/java/com/prgrms/tenwonmoa/domain/user/dto/LoginUserResponse.java
  src/main/java/com/prgrms/tenwonmoa/domain/user/jwt/Jwt.java
  src/main/java/com/prgrms/tenwonmoa/domain/user/jwt/TokenProvider.java
  src/main/java/com/prgrms/tenwonmoa/domain/user/repository/UserRepository.java
  src/main/java/com/prgrms/tenwonmoa/domain/user/service/UserService.java
  src/main/java/com/prgrms/tenwonmoa/exception/message/Message.java
  src/main/resources/application-local.yml
  src/main/resources/application.yml
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/controller/IncomeControllerTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/user/controller/UserControllerTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/user/jwt/JwtTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/user/jwt/TokenProviderTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/user/service/UserServiceTest.java
  src/test/resources/application.yml
  src/test/resources/jwt-config-test.properties
Labels: feature

#71 [#66] 디폴트 카테고리 등록 로직 구현
  src/main/java/com/prgrms/tenwonmoa/config/WebSecurityConfig.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/service/IncomeTotalService.java
  src/main/java/com/prgrms/tenwonmoa/domain/category/Category.java
  src/main/java/com/prgrms/tenwonmoa/domain/category/service/CategoryService.java
  src/main/java/com/prgrms/tenwonmoa/domain/category/service/CreateDefaultUserCategoryService.java
  src/main/java/com/prgrms/tenwonmoa/domain/category/service/FindUserCategoryService.java
  src/main/java/com/prgrms/tenwonmoa/domain/category/service/UserCategoryService.java
  src/main/java/com/prgrms/tenwonmoa/domain/user/dto/LoginUserRequest.java
  src/main/java/com/prgrms/tenwonmoa/domain/user/service/UserService.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/IncomeTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/controller/IncomeControllerTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/service/IncomeTotalServiceTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/category/service/CategoryServiceTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/category/service/CreateDefaultUserCategoryServiceTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/category/service/FindUserCategoryServiceTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/category/service/UserCategoryServiceTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/user/service/UserServiceTest.java
Labels: feature

#76 [#75] 수입 삭제 & 수입관련 서비스 유효성 검사로직 추가
  docs/income.adoc
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/controller/IncomeController.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/repository/IncomeRepository.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/service/IncomeService.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/service/IncomeTotalService.java
  src/main/java/com/prgrms/tenwonmoa/domain/user/User.java
  src/main/java/com/prgrms/tenwonmoa/exception/UnauthorizedUserException.java
  src/main/java/com/prgrms/tenwonmoa/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/prgrms/tenwonmoa/exception/message/Message.java
  src/test/java/com/prgrms/tenwonmoa/common/fixture/RepositoryFixture.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/controller/IncomeControllerTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/repository/IncomeRepositoryTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/service/IncomeServiceTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/service/IncomeTotalServiceTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/user/UserTest.java
Labels: feature, refactor

#77 [#72] REST DOCS 설정 추가
  src/main/java/com/prgrms/tenwonmoa/domain/category/controller/UserCategoryController.java
  src/test/java/com/prgrms/tenwonmoa/common/RestDocsConfig.java
  src/test/java/com/prgrms/tenwonmoa/domain/category/controller/UserCategoryControllerTest.java
Labels: feature

#81 [#34] CORS 설정 추가
  src/main/java/com/prgrms/tenwonmoa/config/ServletConfig.java
Labels: feature

#82 [#34] hotfix: CORS 설정 빠진 부분 추가
  src/main/java/com/prgrms/tenwonmoa/config/ServletConfig.java
Labels: hotfix

#79 [#68] JwtAuthenticationFilter 추가
  src/main/java/com/prgrms/tenwonmoa/config/WebSecurityConfig.java
  src/main/java/com/prgrms/tenwonmoa/domain/user/jwt/Jwt.java
  src/main/java/com/prgrms/tenwonmoa/domain/user/jwt/JwtAuthenticationFilter.java
  src/main/java/com/prgrms/tenwonmoa/domain/user/jwt/TokenProvider.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/controller/IncomeControllerTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/category/controller/UserCategoryControllerTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/user/controller/UserControllerTest.java
Labels: feature
