Repository prgrms-web-devcourse/Team-10jo-10wonmoa-BE, pull requests merged in 2022-08, with the labels that each got.

#80 [#78] 카테고리 등록, 조회, 수정 API 구현
  docs/user-category.adoc
  src/main/java/com/prgrms/tenwonmoa/config/WebSecurityConfig.java
  src/main/java/com/prgrms/tenwonmoa/domain/category/controller/UserCategoryController.java
  src/main/java/com/prgrms/tenwonmoa/domain/category/dto/CreateCategoryRequest.java
  src/test/java/com/prgrms/tenwonmoa/domain/category/controller/UserCategoryControllerTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/user/controller/UserControllerTest.java
Labels: feature

#87 [#34] CORS hot fix
  src/main/java/com/prgrms/tenwonmoa/config/ServletConfig.java
Labels: hotfix

#88 [#34] CORS 설정 드디어 완료
  src/main/java/com/prgrms/tenwonmoa/config/WebSecurityConfig.java
Labels: hotfix

#85 [#84] endpoint에 AuthenticationPrincipal 적용
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/controller/ExpenditureController.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/controller/IncomeController.java
  src/main/java/com/prgrms/tenwonmoa/domain/category/controller/UserCategoryController.java
  src/test/java/com/prgrms/tenwonmoa/common/annotation/WithMockCustomUser.java
  src/test/java/com/prgrms/tenwonmoa/common/annotation/WithMockCustomUserSecurityContextFactory.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/controller/IncomeControllerTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/category/controller/UserCategoryControllerTest.java
Labels: feature

#83 [#64] 사용자는 일별 페이지를 조회한다.(Pagination)
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/Expenditure.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/Income.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/controller/AccountBookQueryController.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/controller/ExpenditureController.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/controller/IncomeController.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/dto/DayDetail.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/dto/FindDayAccountResponse.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/dto/FindDaySumResponse.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/dto/FindMonthSumResponse.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/dto/expenditure/CreateExpenditureRequest.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/dto/expenditure/CreateExpenditureResponse.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/dto/expenditure/FindExpenditureResponse.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/dto/expenditure/UpdateExpenditureRequest.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/dto/income/CreateIncomeRequest.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/dto/income/FindIncomeResponse.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/dto/income/UpdateIncomeRequest.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/repository/AccountBookQueryRepository.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/service/AccountBookQueryService.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/service/ExpenditureService.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/service/IncomeService.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/service/IncomeTotalService.java
  src/main/java/com/prgrms/tenwonmoa/domain/common/BaseEntity.java
  src/main/java/com/prgrms/tenwonmoa/domain/common/page/ChunksCustom.java
  src/main/java/com/prgrms/tenwonmoa/domain/common/page/PageCustomImpl.java
  src/main/java/com/prgrms/tenwonmoa/domain/common/page/PageCustomRequest.java
  src/test/java/com/prgrms/tenwonmoa/config/TestConfig.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/ExpenditureTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/IncomeTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/controller/IncomeControllerTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/repository/AccountBookQueryRepositoryTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/service/ExpenditureServiceTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/service/IncomeServiceTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/service/IncomeTotalServiceTest.java
Labels: feature

#94 [#91] Flyway 적용
  build.gradle
  src/main/resources/application-local.yml
  src/main/resources/db/migration/V1_0_1__table_init.sql
Labels: feature

#98 [#95] DTO Validation Error message 추가
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/dto/expenditure/CreateExpenditureRequest.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/dto/expenditure/UpdateExpenditureRequest.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/dto/income/CreateIncomeRequest.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/dto/income/UpdateIncomeRequest.java
  src/main/java/com/prgrms/tenwonmoa/domain/category/dto/CreateCategoryRequest.java
Labels: feature

#93 [#50] 비밀번호 암호화 추가
  src/main/java/com/prgrms/tenwonmoa/config/WebSecurityConfig.java
  src/main/java/com/prgrms/tenwonmoa/domain/user/User.java
  src/main/java/com/prgrms/tenwonmoa/domain/user/dto/CreateUserRequest.java
  src/main/java/com/prgrms/tenwonmoa/domain/user/service/UserService.java
  src/test/java/com/prgrms/tenwonmoa/domain/user/UserTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/user/service/UserServiceTest.java
Labels: feature

#100 [#99] 토큰 response body, Cookie로 반환
  src/main/java/com/prgrms/tenwonmoa/config/ServletConfig.java
  src/main/java/com/prgrms/tenwonmoa/domain/user/controller/UserController.java
Labels: refactor

#107 [#69] 시큐리티 파일들 user.security 패키지로 이동
  src/main/java/com/prgrms/tenwonmoa/config/WebSecurityConfig.java
  src/main/java/com/prgrms/tenwonmoa/domain/user/security/jwt/Jwt.java
  src/main/java/com/prgrms/tenwonmoa/domain/user/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/prgrms/tenwonmoa/domain/user/security/jwt/TokenProvider.java
  src/main/java/com/prgrms/tenwonmoa/domain/user/service/UserService.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/controller/IncomeControllerTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/category/controller/UserCategoryControllerTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/user/controller/UserControllerTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/user/jwt/TokenProviderTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/user/service/UserServiceTest.java
Labels: refactor

#106 [#105] 수입컨트롤러에서 userService제거
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/controller/IncomeController.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/service/IncomeService.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/service/IncomeTotalService.java
  src/main/java/com/prgrms/tenwonmoa/domain/user/User.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/service/IncomeServiceTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/service/IncomeTotalServiceTest.java
Labels: refactor

#109 [#97] 카테고리 삭제 시, userCategory 삭제안하고 category만 삭제되도록 수정
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/Expenditure.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/Income.java
  src/main/java/com/prgrms/tenwonmoa/domain/category/UserCategory.java
  src/main/java/com/prgrms/tenwonmoa/domain/category/repository/UserCategoryRepository.java
  src/main/java/com/prgrms/tenwonmoa/domain/category/service/UserCategoryService.java
  src/main/java/com/prgrms/tenwonmoa/exception/handler/GlobalExceptionHandler.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/ExpenditureTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/IncomeTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/category/UserCategoryTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/category/repository/UserCategoryRepositoryTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/category/service/UserCategoryServiceTest.java
Labels: bug

#113 [#112] swagger 연동 의존성 및 config 추가
  .github/workflows/tenwonmoa-ci.yml
  build.gradle
  docker-compose-dev.yml
  scripts/deploy.sh
  src/main/java/com/prgrms/tenwonmoa/config/ServletConfig.java
  src/main/java/com/prgrms/tenwonmoa/config/WebSecurityConfig.java
  src/main/resources/static/docs/openapi3.yaml
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/controller/IncomeControllerTest.java
Labels: feature

#115 [#110] 수입 상세조회, 업데이트, 생성 변경
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/Income.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/controller/IncomeController.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/dto/income/FindIncomeResponse.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/dto/income/UpdateIncomeRequest.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/service/IncomeService.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/service/IncomeTotalService.java
  src/main/java/com/prgrms/tenwonmoa/domain/category/CategoryType.java
  src/main/resources/static/docs/openapi3.yaml
  src/test/java/com/prgrms/tenwonmoa/common/documentdto/FindIncomeResponseDoc.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/controller/IncomeControllerTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/service/IncomeServiceTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/service/IncomeTotalServiceTest.java
Labels: refactor

#116 [#103] 일별 상세내역 쿼리 리팩터
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/Expenditure.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/Income.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/dto/DayDetail.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/dto/FindDayAccountResponse.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/repository/AccountBookQueryRepository.java
  src/main/java/com/prgrms/tenwonmoa/domain/common/page/PageCustomImpl.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/repository/AccountBookQueryRepositoryTest.java
Labels: refactor

#117 [#108] 로그인 시 refresh-token 발급
  src/main/java/com/prgrms/tenwonmoa/config/JwtConfigure.java
  src/main/java/com/prgrms/tenwonmoa/config/WebSecurityConfig.java
  src/main/java/com/prgrms/tenwonmoa/domain/user/controller/UserController.java
  src/main/java/com/prgrms/tenwonmoa/domain/user/dto/TokenResponse.java
  src/main/java/com/prgrms/tenwonmoa/domain/user/security/jwt/Jwt.java
  src/main/java/com/prgrms/tenwonmoa/domain/user/security/jwt/RefreshToken.java
  src/main/java/com/prgrms/tenwonmoa/domain/user/security/jwt/TokenProvider.java
  src/main/java/com/prgrms/tenwonmoa/domain/user/security/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/com/prgrms/tenwonmoa/domain/user/security/jwt/repository/RefreshTokenRepository.java
  src/main/java/com/prgrms/tenwonmoa/domain/user/security/jwt/service/JwtService.java
  src/main/java/com/prgrms/tenwonmoa/domain/user/security/jwt/service/TokenProvider.java
  src/main/java/com/prgrms/tenwonmoa/domain/user/service/UserService.java
  src/main/resources/application-local.yml
  src/main/resources/db/migration/V1_0_2__refresh_token_add.sql
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/controller/IncomeControllerTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/category/controller/UserCategoryControllerTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/user/controller/UserControllerTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/user/security/jwt/JwtTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/user/security/jwt/service/TokenProviderTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/user/service/UserServiceTest.java
  src/test/resources/application.yml
  src/test/resources/jwt-config-test.properties
Labels: feature

#122 [#96] 지출, 카테고리, 수입에서 user 검증 로직 통일 & 빠진 부분 추가
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/Income.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/service/ExpenditureService.java
  src/main/java/com/prgrms/tenwonmoa/domain/category/service/UserCategoryService.java
  src/main/java/com/prgrms/tenwonmoa/domain/user/User.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/service/ExpenditureServiceTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/service/IncomeServiceTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/service/IncomeTotalServiceTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/category/service/UserCategoryServiceTest.java
Labels: bug

#124 [#123] 카테고리 컨트롤러 통합 테스트 작성
  src/test/java/com/prgrms/tenwonmoa/common/BaseControllerIntegrationTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/category/controller/UserCategoryControllerIntegrationTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/category/controller/UserCategoryControllerUnitTest.java
Labels: feature

#126 [#102] 수입, 지출, 총합 key incomeSum, expenditureSum, totalSum으로 수정 - responseDto 재사용 + 프론트 type 통일
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/controller/AccountBookQueryController.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/dto/FindDayAccountResponse.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/dto/FindDaySumResponse.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/dto/FindMonthSumResponse.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/dto/FindSumResponse.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/repository/AccountBookQueryRepository.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/service/AccountBookQueryService.java
  src/main/resources/static/docs/openapi3.yaml
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/repository/AccountBookQueryRepositoryTest.java
Labels: refactor

#129 [#128] 수입 컨트롤러 통합테스트 작성
  src/test/java/com/prgrms/tenwonmoa/common/BaseControllerIntegrationTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/controller/IncomeIntegrationTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/category/controller/UserCategoryControllerIntegrationTest.java
Labels: feature

#133 [#125] 검색 API - 리포지토리 구현
  build.gradle
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/AccountBookConst.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/repository/AccountBookSearchRepository.java
  src/test/java/com/prgrms/tenwonmoa/common/annotation/CustomDataJpaTest.java
  src/test/java/com/prgrms/tenwonmoa/config/TestConfig.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/repository/AccountBookSearchRepositoryTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/repository/ExpenditureRepositoryTest.java
Labels: feature

#132 [#114] access-token 만료 시 access-token 재발급
  src/main/java/com/prgrms/tenwonmoa/config/WebSecurityConfig.java
  src/main/java/com/prgrms/tenwonmoa/domain/user/controller/UserController.java
  src/main/java/com/prgrms/tenwonmoa/domain/user/dto/RefreshTokenRequest.java
  src/main/java/com/prgrms/tenwonmoa/domain/user/security/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/com/prgrms/tenwonmoa/domain/user/security/jwt/repository/RefreshTokenRepository.java
  src/main/java/com/prgrms/tenwonmoa/domain/user/security/jwt/service/JwtService.java
  src/main/java/com/prgrms/tenwonmoa/domain/user/security/jwt/service/TokenProvider.java
  src/main/java/com/prgrms/tenwonmoa/domain/user/service/UserService.java
  src/main/java/com/prgrms/tenwonmoa/exception/InvalidTokenException.java
  src/main/java/com/prgrms/tenwonmoa/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/prgrms/tenwonmoa/exception/message/Message.java
  src/test/java/com/prgrms/tenwonmoa/domain/user/security/jwt/service/JwtServiceTest.java
Labels: feature

#137 [#130] 통계 데이터 조회 쿼리구현
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/dto/statistics/FindStatisticsData.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/repository/StatisticsQueryRepository.java
  src/test/java/com/prgrms/tenwonmoa/common/fixture/RepositoryFixture.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/repository/StatisticsQueryRepositoryTest.java
Labels: feature

#142 [#136] 검색 API 컨트롤러 구현 & 테스트
  docs/search-account-book.adoc
  docs/user-category.adoc
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/controller/SearchAccountBookController.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/dto/FindAccountBookResponse.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/dto/service/SearchAccountBookCmd.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/service/SearchAccountBookService.java
  src/main/java/com/prgrms/tenwonmoa/domain/category/UserCategory.java
  src/main/java/com/prgrms/tenwonmoa/domain/category/dto/FindCategoryResponse.java
  src/main/java/com/prgrms/tenwonmoa/domain/category/repository/UserCategoryRepository.java
  src/main/java/com/prgrms/tenwonmoa/domain/category/service/FindUserCategoryService.java
  src/main/java/com/prgrms/tenwonmoa/domain/user/security/jwt/service/TokenProvider.java
  src/test/java/com/prgrms/tenwonmoa/common/BaseControllerIntegrationTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/controller/SearchAccountBookControllerTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/controller/SearchAccountBookIntegrationTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/category/UserCategoryTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/category/repository/UserCategoryRepositoryTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/category/service/FindUserCategoryServiceTest.java
Labels: feature

#143 [#138] 통계조회 서비스, 컨트롤러 구현
  docs/statistics.adoc
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/controller/StatisticsController.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/dto/statistics/FindStatisticsData.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/dto/statistics/FindStatisticsResponse.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/repository/StatisticsQueryRepository.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/service/StatisticsService.java
  src/main/resources/static/docs/openapi3.yaml
  src/test/java/com/prgrms/tenwonmoa/common/documentdto/FindStatisticsDataDoc.java
  src/test/java/com/prgrms/tenwonmoa/common/documentdto/FindStatisticsResponseDoc.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/controller/IncomeIntegrationTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/controller/StatisticsControllerTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/service/StatisticsServiceTest.java
Labels: feature

#146 [#127] 월별 탭 api 작성 - 월별 상세 내역 + 연간 합계 내역
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/controller/AccountBookQueryController.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/dto/DayDetail.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/dto/FindMonthAccountResponse.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/dto/MonthCondition.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/dto/MonthDetail.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/repository/AccountBookQueryRepository.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/service/AccountBookQueryService.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/repository/AccountBookQueryRepositoryTest.java
Labels: feature

#145 [#144] 통계조회 통합테스트 및 유효성검사 추가
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/controller/StatisticsController.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/dto/statistics/FindStatisticsRequest.java
  src/main/java/com/prgrms/tenwonmoa/exception/handler/GlobalExceptionHandler.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/controller/StatisticsIntegrationTest.java
Labels: feature

#154 [#151] 인증 실패 담당 AuthenticationEntryPoint 추가
  src/main/java/com/prgrms/tenwonmoa/config/WebSecurityConfig.java
  src/main/java/com/prgrms/tenwonmoa/domain/user/security/jwt/filter/CustomAuthenticationEntryPoint.java
  src/main/java/com/prgrms/tenwonmoa/domain/user/security/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/com/prgrms/tenwonmoa/exception/message/Message.java
Labels: refactor

#156 [#140] union 쿼리로 지출, 수입 한번에 페이징 처리해서 가져오기
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/dto/AccountBookItem.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/dto/FindDayAccountResponse.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/repository/AccountBookQueryRepository.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/repository/SearchAccountBookRepository.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/repository/SearchAccountBookRepositoryTest.java
Labels: feature

#161 [#153] 지출 등록과 조회 Docs 테스트 진행
  build.gradle
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/dto/expenditure/CreateExpenditureRequest.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/dto/expenditure/CreateExpenditureResponse.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/dto/expenditure/FindExpenditureResponse.java
  src/main/java/com/prgrms/tenwonmoa/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/prgrms/tenwonmoa/exception/message/Message.java
  src/main/resources/static/docs/openapi3.yaml
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/controller/docs/ExpenditureDocsTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/controller/docs/IncomeDocsTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/controller/docs/SearchAccountBookDocsTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/controller/docs/StatisticsDocsTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/controller/intergration/IncomeIntegrationTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/controller/intergration/SearchAccountBookIntegrationTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/controller/intergration/StatisticsIntegrationTest.java
Labels: feature

#158 [#157] 검색API - 개선된 쿼리 활용하여 서비스 & 테스트 수정
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/dto/FindAccountBookResponse.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/repository/SearchAccountBookRepository.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/service/SearchAccountBookService.java
  src/main/resources/static/docs/openapi3.yaml
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/controller/docs/SearchAccountBookDocsTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/controller/docs/StatisticsDocsTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/controller/intergration/SearchAccountBookIntegrationTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/service/SearchAccountBookServiceTest.java
Labels: feature

#160 [#159] 패키지 명 변경
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/controller/IncomeController.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/controller/intergration/IncomeIntegrationTest.java
Labels: bug

#164 [#163] 검색 API 반환값 추가
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/controller/SearchAccountBookController.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/dto/FindAccountBookResponse.java
  src/main/resources/static/docs/openapi3.yaml
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/controller/docs/SearchAccountBookDocsTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/controller/intergration/SearchAccountBookIntegrationTest.java
Labels: feature

#167 [#162] 달력 API 작성
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/controller/AccountBookQueryController.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/dto/CalendarCondition.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/dto/DateDetail.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/dto/FindCalendarResponse.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/repository/AccountBookQueryRepository.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/service/AccountBookQueryService.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/repository/AccountBookQueryRepositoryTest.java
Labels: feature

#169 [#155] 예산 등록 or 수정 API 구현
  build.gradle
  docs/budget.adoc
  src/main/java/com/prgrms/tenwonmoa/domain/budget/Budget.java
  src/main/java/com/prgrms/tenwonmoa/domain/budget/controller/BudgetController.java
  src/main/java/com/prgrms/tenwonmoa/domain/budget/converter/YearMonthIntegerAttributeConverter.java
  src/main/java/com/prgrms/tenwonmoa/domain/budget/dto/CreateOrUpdateBudgetRequest.java
  src/main/java/com/prgrms/tenwonmoa/domain/budget/repository/BudgetRepository.java
  src/main/java/com/prgrms/tenwonmoa/domain/budget/service/BudgetService.java
  src/main/java/com/prgrms/tenwonmoa/domain/budget/service/BudgetTotalService.java
  src/main/resources/static/docs/openapi3.yaml
  src/test/java/com/prgrms/tenwonmoa/common/documentdto/CreateOrUpdateBudgetRequestDoc.java
  src/test/java/com/prgrms/tenwonmoa/domain/budget/BudgetTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/budget/controller/docs/BudgetControllerTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/budget/controller/intergration/BudgetIntegrationTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/budget/repository/BudgetRepositoryTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/budget/service/BudgetTotalServiceTest.java
Labels: feature

#166 [#165] 검색 API 테스트 리팩토링 & 보완
  docs/budget.adoc
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/controller/SearchAccountBookController.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/service/SearchAccountBookService.java
  src/main/java/com/prgrms/tenwonmoa/domain/budget/Budget.java
  src/main/java/com/prgrms/tenwonmoa/domain/common/page/PageCustomRequest.java
  src/main/java/com/prgrms/tenwonmoa/exception/handler/GlobalExceptionHandler.java
  src/main/resources/static/docs/openapi3.yaml
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/controller/docs/SearchAccountBookDocsTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/controller/intergration/SearchAccountBookIntegrationTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/repository/SearchAccountBookRepositoryTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/service/SearchAccountBookServiceTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/budget/BudgetTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/budget/service/BudgetTotalServiceTest.java
Labels: feature

#174 [#171] 다른 유저의 카테고리 등록못하게 변경
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/service/IncomeTotalService.java
  src/main/java/com/prgrms/tenwonmoa/domain/budget/service/BudgetTotalService.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/controller/intergration/IncomeIntegrationTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/service/IncomeTotalServiceTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/budget/controller/intergration/BudgetIntegrationTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/budget/service/BudgetTotalServiceTest.java
Labels: bug

#176 [#175] 월 별 예산내역 조회 구현
  docs/budget.adoc
  src/main/java/com/prgrms/tenwonmoa/domain/budget/Budget.java
  src/main/java/com/prgrms/tenwonmoa/domain/budget/controller/BudgetController.java
  src/main/java/com/prgrms/tenwonmoa/domain/budget/dto/FindBudgetData.java
  src/main/java/com/prgrms/tenwonmoa/domain/budget/dto/FindBudgetResponse.java
  src/main/java/com/prgrms/tenwonmoa/domain/budget/repository/BudgetRepository.java
  src/main/java/com/prgrms/tenwonmoa/domain/budget/service/BudgetService.java
  src/main/resources/static/docs/openapi3.yaml
  src/test/java/com/prgrms/tenwonmoa/common/documentdto/FindBudgetDataDoc.java
  src/test/java/com/prgrms/tenwonmoa/common/fixture/RepositoryFixture.java
  src/test/java/com/prgrms/tenwonmoa/domain/budget/controller/docs/BudgetControllerTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/budget/controller/intergration/BudgetIntegrationTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/budget/repository/BudgetRepositoryTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/budget/service/BudgetServiceTest.java
Labels: feature

#178 지출 -> 수입으로 바뀔 때 해당 건의 대한 타입이 INCOME으로 바뀌지 않는 문제 해결
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/service/ExpenditureService.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/service/ExpenditureServiceTest.java
Labels: bug

#180 [#179] 마이페이지 유저 정보 조회 API
  docs/user.adoc
  src/main/java/com/prgrms/tenwonmoa/domain/user/controller/UserController.java
  src/main/java/com/prgrms/tenwonmoa/domain/user/dto/FindUserResponse.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/controller/intergration/SearchAccountBookIntegrationTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/repository/SearchAccountBookRepositoryTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/user/controller/UserControllerTest.java
Labels: feature

#181 [#173] google 로그인 후 토큰 생성
  src/main/java/com/prgrms/tenwonmoa/config/WebSecurityConfig.java
  src/main/java/com/prgrms/tenwonmoa/domain/user/security/oauth2/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/prgrms/tenwonmoa/domain/user/security/oauth2/OAuth2UserPrincipal.java
  src/main/java/com/prgrms/tenwonmoa/domain/user/security/oauth2/handler/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/prgrms/tenwonmoa/domain/user/security/oauth2/service/OAuth2UserDetailsService.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/controller/docs/IncomeDocsTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/user/controller/UserControllerTest.java
Labels: feature

#186 [#183] 사용자 예산정보 조회로직변경
  src/main/java/com/prgrms/tenwonmoa/domain/budget/controller/BudgetController.java
  src/main/java/com/prgrms/tenwonmoa/domain/budget/dto/FindBudgetData.java
  src/main/java/com/prgrms/tenwonmoa/domain/budget/repository/BudgetQueryRepository.java
  src/main/java/com/prgrms/tenwonmoa/domain/budget/repository/BudgetRepository.java
  src/main/java/com/prgrms/tenwonmoa/domain/budget/service/BudgetService.java
  src/main/java/com/prgrms/tenwonmoa/domain/budget/service/BudgetTotalService.java
  src/test/java/com/prgrms/tenwonmoa/common/fixture/RepositoryFixture.java
  src/test/java/com/prgrms/tenwonmoa/domain/budget/controller/docs/BudgetControllerTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/budget/repository/BudgetQueryRepositoryTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/budget/repository/BudgetRepositoryTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/budget/service/BudgetServiceTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/budget/service/BudgetTotalServiceTest.java
Labels: feature, refactor

#189 [#188] AOP - logging과 performance
  src/main/java/com/prgrms/tenwonmoa/aop/LoggingAspect.java
  src/main/java/com/prgrms/tenwonmoa/aop/PerformanceAspect.java
  src/main/java/com/prgrms/tenwonmoa/filter/ReadableRequestWrapperFilter.java
Labels: feature

#192 [#191] 카테고리 삭제 버그 수정
  src/main/java/com/prgrms/tenwonmoa/domain/category/service/UserCategoryService.java
  src/main/resources/db/migration/V1_0_3__user_category_category_nullable.sql
Labels: bug

#195 [#193] {date} pathVariable이 아닌 queryString으로 year와 month 따로 받기
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/controller/AccountBookQueryController.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/dto/CalendarCondition.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/repository/AccountBookQueryRepository.java
  src/main/java/com/prgrms/tenwonmoa/exception/message/Message.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/repository/AccountBookQueryRepositoryTest.java
Labels: refactor

#203 [#201] 구글 로그인 중 username 오류 해결
  src/main/java/com/prgrms/tenwonmoa/domain/user/User.java
  src/main/java/com/prgrms/tenwonmoa/domain/user/security/oauth2/service/OAuth2UserDetailsService.java
  src/main/resources/db/migration/V1_0_4__user_from_social_add.sql
Labels: hotfix

#204 [#199] flyway plugin 추가
  build.gradle
  src/test/resources/application.yml
Labels: feature

#206 [#205] CI/CD 구분. github workflow
  .github/workflows/tenwonmoa-ci.yml
  .github/workflows/tenwonmoa-cicd.yml
Labels: feature

#202 [#200] 배너는 프로젝트의 마무리
  src/main/resources/banner.txt
Labels: feature

#207 [#187] 월, 연별 예산 데이터 조회 구현
  src/main/java/com/prgrms/tenwonmoa/domain/budget/Budget.java
  src/main/java/com/prgrms/tenwonmoa/domain/budget/controller/BudgetController.java
  src/main/java/com/prgrms/tenwonmoa/domain/budget/dto/FindBudgetByRegisterDate.java
  src/main/java/com/prgrms/tenwonmoa/domain/budget/dto/FindBudgetWithExpenditureRequest.java
  src/main/java/com/prgrms/tenwonmoa/domain/budget/dto/FindBudgetWithExpenditureResponse.java
  src/main/java/com/prgrms/tenwonmoa/domain/budget/repository/BudgetQueryRepository.java
  src/main/java/com/prgrms/tenwonmoa/domain/budget/service/BudgetTotalService.java
  src/test/java/com/prgrms/tenwonmoa/domain/budget/BudgetTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/budget/repository/BudgetQueryRepositoryTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/budget/service/BudgetTotalServiceTest.java
Labels: feature

#211 제닛 요청으로 int day를 Localdate date로 변환
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/dto/DateDetail.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/repository/AccountBookQueryRepository.java
Labels: refactor

#214 [#172] 에러 핸들링 정리
  src/main/java/com/prgrms/tenwonmoa/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/prgrms/tenwonmoa/exception/message/Message.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/controller/docs/ExpenditureDocsTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/controller/docs/IncomeDocsTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/controller/intergration/SearchAccountBookIntegrationTest.java
Labels: feature

#219 [#215] 검색 합계 API 구현 [리포지토리]
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/controller/SearchAccountBookController.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/dto/FindAccountBookResponse.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/dto/service/SearchAccountBookCmd.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/repository/ExpenditureRepository.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/repository/IncomeRepository.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/repository/SearchAccountBookRepository.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/service/SearchAccountBookService.java
  src/main/java/com/prgrms/tenwonmoa/exception/message/Message.java
  src/test/java/com/prgrms/tenwonmoa/common/fixture/RepositoryFixture.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/controller/docs/SearchAccountBookDocsTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/controller/intergration/SearchAccountBookIntegrationTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/repository/ExpenditureRepositoryTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/repository/IncomeRepositoryTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/repository/SearchAccountBookRepositoryTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/service/SearchAccountBookServiceTest.java
Labels: feature

#220 [#216] 회원 탈퇴
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/repository/ExpenditureRepository.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/repository/IncomeRepository.java
  src/main/java/com/prgrms/tenwonmoa/domain/budget/repository/BudgetRepository.java
  src/main/java/com/prgrms/tenwonmoa/domain/category/repository/UserCategoryRepository.java
  src/main/java/com/prgrms/tenwonmoa/domain/user/controller/UserController.java
  src/main/java/com/prgrms/tenwonmoa/domain/user/security/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/com/prgrms/tenwonmoa/domain/user/service/UserDeleteService.java
  src/main/java/com/prgrms/tenwonmoa/domain/user/service/UserService.java
  src/test/java/com/prgrms/tenwonmoa/domain/user/service/UserDeleteServiceTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/user/service/UserServiceTest.java
Labels: feature

#222 [#197] 일일 상세내역 paging을 날짜가아닌 지출과 수입의 건으로 pagination version 2
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/controller/AccountBookQueryController.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/dto/YearMonthCondition.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/repository/AccountBookQueryRepository.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/service/AccountBookQueryService.java
  src/main/java/com/prgrms/tenwonmoa/domain/common/page/PageInternalElementsImpl.java
  src/main/java/com/prgrms/tenwonmoa/domain/common/page/PageResponse.java
  src/main/java/com/prgrms/tenwonmoa/exception/message/Message.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/repository/AccountBookQueryRepositoryTest.java
Labels: feature

#225 [#215] 검색 합계 반환 API -서비스, 컨트롤러
  docs/search-account-book.adoc
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/controller/SearchAccountBookController.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/dto/FindAccountBookSumResponse.java
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/service/SearchAccountBookService.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/controller/docs/SearchAccountBookDocsTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/controller/intergration/SearchAccountBookIntegrationTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/service/SearchAccountBookServiceTest.java
Labels: feature

#230 [#229] 유저 정보 조회시 토큰 값이 비었을 때 생기는 오류 해결
  src/main/java/com/prgrms/tenwonmoa/config/WebSecurityConfig.java
  src/main/java/com/prgrms/tenwonmoa/domain/user/security/jwt/filter/JwtAuthenticationFilter.java
Labels: bug

#231 [#217] 비밀번호 확인 로직 추가
  src/main/java/com/prgrms/tenwonmoa/domain/user/controller/UserController.java
  src/main/java/com/prgrms/tenwonmoa/domain/user/dto/CheckPasswordRequest.java
  src/main/java/com/prgrms/tenwonmoa/domain/user/service/UserService.java
Labels: feature

#233 [#232] 지출 docs 통합 테스트 마무리
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/controller/docs/ExpenditureDocsTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/controller/intergration/ExpenditureIntergrationTest.java
Labels: feature

#237 [#234] 가계부 docs 통합테스트 마무리
  docs/account-book.adoc
  docs/expenditure.adoc
  src/main/resources/static/docs/openapi3.yaml
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/controller/docs/AccountBookDocsTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/controller/docs/ExpenditureDocsTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/controller/intergration/AccountBookIntergrationTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/accountbook/service/AccountBookQueryServiceTest.java
Labels: feature

#242 overview.adoc 추가
  .github/workflows/pages.yml
  README.md
  docs/index.html
  docs/overview.adoc
Labels: feature

#246 [#104] UserController 유닛 테스트 추가
  README.md
  docs/user.adoc
  src/main/java/com/prgrms/tenwonmoa/domain/accountbook/dto/condition/MonthCondition.java
  src/main/resources/static/docs/openapi3.yaml
  src/test/java/com/prgrms/tenwonmoa/domain/user/controller/UserControllerTest.java
  src/test/java/com/prgrms/tenwonmoa/domain/user/controller/docs/UserControllerDocsTest.java
Labels: feature
